# Generated by Django 3.2 on 2023-07-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
