# Generated by Django 3.2 on 2023-08-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0003_alter_doc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
