# Generated by Django 3.2 on 2023-08-08 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0004_doc_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='version',
        ),
    ]
