# Generated by Django 3.2 on 2023-08-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0005_remove_doc_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='title',
            field=models.CharField(default='Doc heading', max_length=120),
            preserve_default=False,
        ),
    ]
