# Generated by Django 3.2 on 2023-08-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0007_auto_20230809_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
