# Generated by Django 3.2 on 2023-07-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230722_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='defaultUsername', max_length=30, unique=True),
        ),
    ]
